function gears = gearRegistry()
%GEARREGISTRY The list of active gears. Add a gear by adding one file
%   under +gears/ that returns a struct with the required fields (see
%   validateGear.m) and one line here - no other file needs to change
%   (contrast with the original codebase, where a new modulation family
%   meant editing an if/elseif dispatch in three separate files).
gears = { ...
    gearboxphy.gears.qamGear(), ...
    gearboxphy.gears.naQamGear(), ...
    gearboxphy.gears.zxmGear(), ...
    gearboxphy.gears.pulseGear("Energy"), ...
    gearboxphy.gears.pulseGear("Arbitrary") ...
};
for i = 1:numel(gears)
    gearboxphy.gears.validateGear(gears{i});
end
end
