function scenario = makeScenarioConfig(opts)
%MAKESCENARIOCONFIG Builds one validated scenario struct, replacing
%   Wrapper.m's ~60 lines of bare `params.x=...` assignment. Uses an
%   `arguments` block for validation - no class needed for that. Defaults
%   match Wrapper.m's original values exactly.
arguments
    opts.eta (1,1) double = 0.1
    opts.epsilon_trans (1,1) double = 0.01
    opts.epsilon_rec (1,1) double = 0.5
    opts.alpha (1,1) double {mustBeInRange(opts.alpha,0,1)} = 0.5
    opts.N_0 (1,1) double = 1.380649e-23*295
    opts.beta (1,1) double = 2
    opts.c (1,1) double = 3e8
    opts.c_PA (1,1) double = 4.32e-5
    opts.c_ADC (1,1) double = 0.67e-15
    opts.f_b (1,1) double = 560e6
    opts.NoiseFigure (1,1) double = 10
    opts.Maximum_P_T (1,1) double = 10
    opts.D_r (1,1) double = 6
    opts.D_t (1,1) double = 6
    opts.gamma_MOS (1,1) double = 1
    opts.DAC_VDD (1,1) double = 3
    opts.DAC_Cp (1,1) double = 1e-12*1/2
    opts.DAC_I0 (1,1) double = 10e-6
    opts.P_ED (1,1) double = 2.4e-3
    opts.distance (1,1) double {mustBePositive} = 50
    opts.pulseFilter (1,1) string = "rc"
    opts.dataDir (1,1) string = "SE_data"
    opts.RVec (1,:) double = logspace(3,11,400)
    opts.fcVec (1,:) double = [2.4 8 28 60]*1e9
    opts.maxiters (1,1) double = 5e3
    opts.tolerance (1,1) double = 1e-10
    opts.numtriesPerOpt (1,1) double = 20
    opts.maxCores (1,1) double = 200
    % QAM MIMO antenna-configuration candidates (MIMO_EXTENSION.md) - a
    % cell array of struct('N_t',N_t,'N_r',N_r). Default is SISO-only, so
    % enabling MIMO is a config change (pass e.g.
    % {struct('N_t',1,'N_r',1), struct('N_t',2,'N_r',2)}), not a code
    % change. Requires matching SE_data/SE_<M>_QAM_<N_t>x<N_r>.mat files
    % to exist for every non-SISO candidate (MIMO_EXTENSION.md decision
    % 3: these are frozen, externally-supplied inputs, not generated by
    % this framework).
    opts.qamMimoConfigs (1,:) cell = {struct('N_t', 1, 'N_r', 1)}
    % What multiple antennas are USED FOR (BEAMFORMING_EXTENSION.md).
    %   "multiplexing" (default) - today's behaviour, byte-identical: a
    %       non-SISO config needs its own SE_data MIMO curve carrying N_t
    %       independent streams, and the path loss is unaware of antenna
    %       count.
    %   "beamforming"  - the array is used for GAIN, not for streams. The
    %       SISO SE curve is used for EVERY antenna config (one stream,
    %       unchanged mutual information), and the array instead buys an
    %       ideal path-loss gain of N_t*N_r. Hardware power keeps scaling
    %       per chain exactly as in the multiplexing case.
    opts.antennaMode (1,1) string {mustBeMember(opts.antennaMode, ["multiplexing","beamforming"])} = "multiplexing"
    % Antenna-config candidates in beamforming mode, for QAM *and* ZXM.
    % Unlike qamMimoConfigs these need no SE_data of their own (the SISO
    % curve is reused), so any (N_t,N_r) is admissible.
    opts.beamformingConfigs (1,:) cell = {struct('N_t', 1, 'N_r', 1)}
    % PA power model trigger (PA_POWER_MODEL_DECISION.md). "constant"
    % (default, Model A) matches the original dissertation formula
    % exactly - PA power is scale-invariant in antenna count regardless
    % of P_0. "affine" (Model B) adds a fixed N_t*P_0 per-PA overhead
    % term (Auer et al. 2011) - requires P_0 to be set (see below).
    opts.paPowerModel (1,1) string {mustBeMember(opts.paPowerModel, ["constant","affine"])} = "constant"
    % Fixed per-PA overhead power [W], only used when paPowerModel is
    % "affine". Left as NaN by default so accidentally switching to
    % "affine" without supplying a real value fails loudly (qamGear.m)
    % rather than silently running with P_0=0 (which would make "affine"
    % indistinguishable from "constant").
    opts.P_0 (1,1) double = NaN
    % LNA power model (LNA_POWER_MODEL.md, +physics/lnaPowerFor.m).
    %   "fom_bandwidth" (default) - the dissertation's lnaPower.m,
    %       byte-identical to every existing result.
    %   "fom_floor"  - same formula, bandwidth floored at lnaBetaMin*f_c
    %       (an LNA cannot be built narrower than that).
    %   "envelope"   - 5 % lower envelope of the Belostotski LNA survey,
    %       same floor (+physics/lnaPowerEnvelope.m).
    opts.lnaPowerModel (1,1) string {mustBeMember(opts.lnaPowerModel, ["fom_bandwidth","fom_floor","envelope"])} = "fom_bandwidth"
    % Minimum LNA fractional bandwidth for "fom_floor"/"envelope" (the
    % survey's 5th percentile). Ignored by "fom_bandwidth".
    opts.lnaBetaMin (1,1) double {mustBePositive} = 0.05
    % ADC power model (docs/ADC_POWER_MODEL.md, +physics/adcConstant.m).
    %   "envelope" (default) - c_ADC as given above (0.67 fJ, the survey's
    %       best-case envelope), byte-identical to every existing result.
    %   "quantile5" - 3.17 fJ, the survey's 5 % quantile in the band the
    %       Gearbox uses. It REPLACES c_ADC, so do not combine it with a
    %       hand-set c_ADC.
    opts.adcPowerModel (1,1) string {mustBeMember(opts.adcPowerModel, ["envelope","quantile5"])} = "envelope"
    % Beamforming architecture (docs/ANALOG_BEAMFORMING.md,
    % +physics/analogBeamformingParams.m). QAM gear only.
    %   "digital" (default) - one converter chain per antenna, as before;
    %       byte-identical to every existing result.
    %   "analog"  - one DAC pair, one ADC pair and one mixer per side, one
    %       phase shifter per element. One stream: needs
    %       antennaMode="beamforming", or analogCurvesCarryArrayGain=true
    %       with single-stream curves that already contain the array gain.
    opts.beamformingArch (1,1) string {mustBeMember(opts.beamformingArch, ["digital","analog"])} = "digital"
    opts.analogCurvesCarryArrayGain (1,1) logical = false
    % Phase shifter for "analog" (docs/PHASE_SHIFTER_POWER_MODEL.md):
    %   "active" - psPower per element, no loss;
    %   "passive_penalty" - no DC power, loss as driver power and noise
    %       penalty (optimistic bound);
    %   "passive_compensated" - loss made up by LNA gain.
    opts.psType (1,1) string {mustBeMember(opts.psType, ["active","passive_penalty","passive_compensated"])} = "active"
    % NaN = per-carrier default of +physics/phaseShifterParams.m.
    opts.psPower (1,1) double = NaN          % [W] per element, active only
    opts.psLossDb (1,1) double = NaN         % [dB] insertion loss, passive only
    % Phase resolution; Inf = no quantisation loss.
    opts.psBits (1,1) double {mustBePositive} = 6
    % Gains behind the passive penalties (phaseShifterPenalty.m).
    % psGainPA = 20 dB is an assumption; the LNA values are lnaPower.m's.
    opts.psGainPA (1,1) double {mustBePositive} = 100
    opts.psGainLNA (1,1) double {mustBePositive} = 32
    opts.psNoiseFactorLNA (1,1) double {mustBePositive} = 3
    % LO distribution (+physics/loDistributionPower.m).
    %   "shared" (default) - one LO per side whatever the number of
    %       mixers; byte-identical to every existing result.
    %   "per_mixer" - every mixer beyond the first adds an LO buffer of
    %       loDistPowerPerMixer. Charges digital arrays (N mixers per
    %       side); analog beamforming has one mixer and is unchanged.
    opts.loDistributionModel (1,1) string {mustBeMember(opts.loDistributionModel, ["shared","per_mixer"])} = "shared"
    % [W] per additional mixer; NaN = per-carrier default (28 GHz: 16.6 mW).
    opts.loDistPowerPerMixer (1,1) double = NaN
    % Per-carrier maximum bandwidth, rows [f_c B_max] in Hz. Empty
    % (default) keeps B_max = eta*f_c. When given, EVERY carrier in fcVec
    % must have a row - resolveScenarioForCarrier.m errors otherwise
    % rather than silently falling back to eta.
    opts.B_maxByCarrier (:,2) double = zeros(0, 2)
end
if opts.beamformingArch == "analog"
    assert(opts.antennaMode == "beamforming" || opts.analogCurvesCarryArrayGain, ...
        'gearboxphy:analogNeedsSingleStream', ...
        ['beamformingArch="analog" needs antennaMode="beamforming", or ' ...
         'analogCurvesCarryArrayGain=true together with single-stream curves ' ...
         'that already contain the array gain.']);
end
scenario = opts;   % plain struct, not an object
end
